import { Command } from "#structures/classes/Command";
import {
  ContainerBuilder,
  TextDisplayBuilder,
  SectionBuilder,
  SeparatorBuilder,
  SeparatorSpacingSize,
  ThumbnailBuilder,
  ActionRowBuilder,
  ButtonBuilder,
  ButtonStyle,
  MessageFlags,
  ChannelType,
} from "discord.js";
import emoji from "#config/emoji";
import { config } from "#config/config";

class ServerInviteCommand extends Command {
  constructor() {
    super({
      name: "serverinvite",
      description: "Generate an invite link for a server",
      usage: "serverinvite <server_id>",
      aliases: ["sinv", "getinvite", "guildinvite"],
      category: "Owner",
      examples: ["serverinvite 123456789"],
      cooldown: 0,
      ownerOnly: true,
    });
  }

  async execute({ client, message, args }) {
    try {
      if (!config.ownerIds?.includes(message.author.id)) {
        return message.reply({
          content: `${emoji.get("cross")} This command is only available to bot owners.`,
        });
      }

      if (!args[0]) {
        return message.reply({
          content: `${emoji.get("cross")} Please provide a server ID!\n**Usage:** \`${this.usage}\``,
        });
      }

      const serverId = args[0];

      if (!/^\d{17,19}$/.test(serverId)) {
        return message.reply({
          content: `${emoji.get("cross")} Invalid server ID format!`,
        });
      }

      const guild = client.guilds.cache.get(serverId);

      if (!guild) {
        return message.reply({
          content: `${emoji.get("cross")} I'm not in a server with that ID!`,
        });
      }

      const textChannel = guild.channels.cache.find(
        (c) => c.type === ChannelType.GuildText && c.permissionsFor(guild.members.me).has("CreateInstantInvite")
      );

      if (!textChannel) {
        return message.reply({
          content: `${emoji.get("cross")} I cannot create an invite for this server (no permissions).`,
        });
      }

      const invite = await textChannel.createInvite({
        maxAge: 86400,
        maxUses: 1,
        reason: `Invite generated by bot owner ${message.author.tag}`,
      });

      const container = new ContainerBuilder();

      container.addTextDisplayComponents(
        new TextDisplayBuilder().setContent(
          `${emoji.get("check")} **Server Invite Generated**`
        )
      );

      container.addSeparatorComponents(
        new SeparatorBuilder().setSpacing(SeparatorSpacingSize.Small)
      );

      const content =
        `**Server:** ${guild.name}\n` +
        `**ID:** \`${guild.id}\`\n` +
        `**Members:** ${guild.memberCount}\n` +
        `**Owner:** ${(await guild.fetchOwner()).user.tag}`;

      const section = new SectionBuilder()
        .addTextDisplayComponents(
          new TextDisplayBuilder().setContent(content)
        )
        .setThumbnailAccessory(
          new ThumbnailBuilder().setURL(
            guild.iconURL({ dynamic: true }) || "https://cdn.discordapp.com/embed/avatars/0.png"
          )
        );

      container.addSectionComponents(section);

      container.addSeparatorComponents(
        new SeparatorBuilder().setSpacing(SeparatorSpacingSize.Small)
      );

      const row = new ActionRowBuilder().addComponents(
        new ButtonBuilder()
          .setLabel("Join Server")
          .setStyle(ButtonStyle.Link)
          .setURL(`https://discord.gg/${invite.code}`)
      );

      container.addActionRowComponents(row);

      container.addTextDisplayComponents(
        new TextDisplayBuilder().setContent(
          `*Invite expires in 24 hours and can only be used once.*`
        )
      );

      await message.reply({
        components: [container],
        flags: MessageFlags.IsComponentsV2,
      });
    } catch (error) {
      client.logger?.error("ServerInviteCommand", `Error: ${error.message}`, error);
      await message.reply({
        content: `${emoji.get("cross")} An error occurred while creating the invite.`,
      });
    }
  }
}

export default new ServerInviteCommand();
